async def run(
    service,
    repository_path: str,
    session_id: str,
    task: str,
    approach: str,
    outcome: str,
    evidence: str,
    affected_files: list[str],
    tests=None,
    failure_reason=None,
    dependency_versions=None,
    summary=None,
):
    return await service.record_outcome(
        repository_path,
        session_id,
        task,
        approach,
        outcome,
        evidence,
        affected_files,
        tests,
        failure_reason,
        dependency_versions,
        summary,
    )
